// Generated by CoffeeScript 1.7.1
(function() {
  var colorNumbers, colorPalette, path, testImage;

  colorPalette = require("./index");

  path = require("path");

  testImage = path.resolve(__dirname, "./test.jpg");

  colorNumbers = 8;

  colorPalette(testImage, colorNumbers, function(err, result) {
    return console.log(err, result);
  });

}).call(this);

//# sourceMappingURL=test.map
