// Generated by CoffeeScript 1.7.1
(function() {
  var colorScript, exec, path;

  exec = require("child_process").exec;

  path = require("path");

  colorScript = path.resolve(__dirname, "./color-palette.sh");

  module.exports = function(imgPath, number, cb, debug) {
    var cmd;
    cmd = "" + colorScript + " " + imgPath + " " + number;
    return exec(cmd, function(err, stdout, stderr) {
      var index, instance, json, result, sum;
      if (err) {
        cb(err);
        if (debug) {
          return console.error(err);
        }
      } else {
        if (stderr && debug) {
          console.warn(stderr);
        }
        if (stdout) {
          result = (function() {
            var _i, _j, _len, _len1, _ref, _ref1;
            try {
              json = JSON.parse(stdout);
              sum = 0;
              _ref = json.result;
              for (_i = 0, _len = _ref.length; _i < _len; _i++) {
                instance = _ref[_i];
                sum += parseInt(instance.counts);
              }
              console.log(sum);
              _ref1 = json.result;
              for (index = _j = 0, _len1 = _ref1.length; _j < _len1; index = ++_j) {
                instance = _ref1[index];
                json.result[index].counts = parseInt(instance.counts);
                json.result[index].percentage = Math.round(parseInt(instance.counts) / parseInt(sum) * 10000) / 100;
                json.result[index].percent = json.result[index].percentage + "%";
              }
              return json;
            } catch (_error) {
              err = _error;
              return stdout;
            }
          })();
          return cb(null, result);
        } else {
          return cb(stderr);
        }
      }
    });
  };

}).call(this);

//# sourceMappingURL=index.map
